// wrapper.mjs — the auto-develop.sh a project keeps. No logic: it names the
// package version and hands over. PIPELINE_BIN points at a local checkout of
// the engine (development, offline use); `init --local` bakes that path in.

import { copyFileSync, existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { git, gitText } from "../util/exec.mjs";

export function wrapperText({ version, harness = null, localBin = null }) {
	const harnessFlag = harness ? ` --harness ${shellQuote(harness)}` : "";
	const lines = [
		"#!/usr/bin/env bash",
		`# auto-develop.sh — generated by \`pi-governance-pipeline init\` (${version}). The loop lives in the package;`,
		"# routing, budgets, gates and the issue source are read from AGENTS.md. Bump the pin to update.",
		'cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1',
		'export PIPELINE_WRAPPER="${BASH_SOURCE[0]##*/}"',
	];
	if (localBin) {
		lines.push(`exec node "\${PIPELINE_BIN:-${localBin.replace(/\\/g, "/")}}" run${harnessFlag} "$@"`);
	} else {
		lines.push(`if [ -n "\${PIPELINE_BIN:-}" ]; then exec node "$PIPELINE_BIN" run${harnessFlag} "$@"; fi`);
		lines.push(`exec npx --yes pi-governance-pipeline@${version} run${harnessFlag} "$@"`);
	}
	return `${lines.join("\n")}\n`;
}

function shellQuote(s) {
	return /^[A-Za-z0-9_=,.:/-]+$/.test(s) ? s : `'${s.replace(/'/g, "'\\''")}'`;
}

export const wrapperEolRule = (file = "auto-develop.sh") => `${file} text eol=lf`;

// The attributes git resolves for the wrapper in `dir`, without the user's own
// attributes file: a rule that lives only in `core.attributesFile` is not part
// of the project and does not travel with a clone.
function resolveAttributes(dir, file) {
	const of = (attr) => {
		const raw = gitText(dir, ["-c", "core.attributesFile=", "check-attr", attr, "--", file]);
		return raw ? raw.slice(raw.lastIndexOf(":") + 1).trim() : "unspecified";
	};
	return { text: of("text"), eol: of("eol") };
}

// What a clone would see: the project's own `.gitattributes`, evaluated by git
// in a scratch repository so that no private file can mask it.
//
// Two failure modes meet here, and only git's own matcher separates them. A
// later rule that cannot match the wrapper (`*.md text`) must not invalidate
// the pin — reading "the last line of the file" as the test cost a warning on
// a correct setup and a duplicate rule on the next `init`. A later rule that
// does match (`*.sh text eol=crlf`) must invalidate it — and `check-attr` in
// the real repository cannot answer that, because `.git/info/attributes` takes
// precedence over `.gitattributes` and is exactly the private file that does
// not survive a clone. Hand-rolling glob semantics to tell the two apart would
// be the third wrong answer; git already has the matcher.
function projectAttributes(root, file) {
	const dir = mkdtempSync(join(tmpdir(), "pipeline-attrs-"));
	try {
		git(dir, ["-c", "init.templateDir=", "init", "-q"]);
		const source = join(root, ".gitattributes");
		if (existsSync(source)) copyFileSync(source, join(dir, ".gitattributes"));
		return resolveAttributes(dir, file);
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
}

// Does the project's own attributes file pin the wrapper to LF, on its own?
export function hasWrapperEolRule(root, file = "auto-develop.sh") {
	const project = projectAttributes(root, file);
	return project.eol === "lf" && project.text !== "unset";
}

// The durable project rule and the effective attributes together. Traps the
// effective answer alone does not catch: a line that reads like a rule and is
// none (`auto-develop.sh linguist-generated=true`), one that pins the opposite
// (`text eol=crlf`), `-text eol=lf` where nothing is normalised because `text`
// is explicitly unset, and a rule supplied only by a private file.
export function wrapperEol(root, file = "auto-develop.sh") {
	const { text, eol } = resolveAttributes(root, file);
	const projectRule = hasWrapperEolRule(root, file);
	return { eol, text, projectRule, lf: projectRule && eol === "lf" && text !== "unset" };
}

// The version a wrapper is pinned to, or null when it is not a generated wrapper.
export function wrapperPin(text) {
	const m = text.match(/pi-governance-pipeline@(\d+\.\d+\.\d+)/) ?? text.match(/init` \((\d+\.\d+\.\d+)\)/);
	return m ? m[1] : null;
}
