// wrapper.mjs — the auto-develop.sh a project keeps. No logic: it names the
// package version and hands over. PIPELINE_BIN points at a local checkout of
// the engine (development, offline use); `init --local` bakes that path in.

export function wrapperText({ version, harness = null, localBin = null }) {
	const harnessFlag = harness ? ` --harness ${shellQuote(harness)}` : "";
	const lines = [
		"#!/usr/bin/env bash",
		`# auto-develop.sh — generated by \`pi-governance-pipeline init\` (${version}). The loop lives in the package;`,
		"# routing, budgets, gates and the issue source are read from AGENTS.md. Bump the pin to update.",
		'cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1',
		'export PIPELINE_WRAPPER="${BASH_SOURCE[0]##*/}"',
	];
	if (localBin) {
		lines.push(`exec node "\${PIPELINE_BIN:-${localBin.replace(/\\/g, "/")}}" run${harnessFlag} "$@"`);
	} else {
		lines.push(`if [ -n "\${PIPELINE_BIN:-}" ]; then exec node "$PIPELINE_BIN" run${harnessFlag} "$@"; fi`);
		lines.push(`exec npx --yes pi-governance-pipeline@${version} run${harnessFlag} "$@"`);
	}
	return `${lines.join("\n")}\n`;
}

function shellQuote(s) {
	return /^[A-Za-z0-9_=,.:/-]+$/.test(s) ? s : `'${s.replace(/'/g, "'\\''")}'`;
}

// The version a wrapper is pinned to, or null when it is not a generated wrapper.
export function wrapperPin(text) {
	const m = text.match(/pi-governance-pipeline@(\d+\.\d+\.\d+)/) ?? text.match(/init` \((\d+\.\d+\.\d+)\)/);
	return m ? m[1] : null;
}
