#!/usr/bin/env bash
# auto-develop.sh — generated by `pi-governance-pipeline init` (1.2.1). The loop lives in the package;
# routing, budgets, gates and the issue source are read from AGENTS.md. Bump the pin to update.
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
export PIPELINE_WRAPPER="${BASH_SOURCE[0]##*/}"
if [ -n "${PIPELINE_BIN:-}" ]; then exec node "$PIPELINE_BIN" run "$@"; fi
exec npx --yes pi-governance-pipeline@1.2.1 run "$@"
